# Generated by Django 4.2.4 on 2025-04-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_pet_notificacao_descricao_consulta_id_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='id_Pet',
            new_name='Pet',
        ),
    ]
