# Generated by Django 4.2.4 on 2025-04-30 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_rename_id_pet_consulta_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='dt_envio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='dt_rspsta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='ip_rspsta',
            field=models.CharField(default='SOME STRING', max_length=15),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='rspsta',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='token',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
