# Generated by Django 4.2.4 on 2025-05-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_consulta_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='rspsta',
        ),
    ]
