# Generated by Django 4.2.4 on 2025-05-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_remove_notificacao_rspsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='rspsta',
            field=models.CharField(choices=[('0', 'Não Aprovado'), ('2', 'Aprovado'), ('3', 'Indefinido')], default='3', max_length=1),
        ),
    ]
