# Generated by Django 4.2.4 on 2025-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_notificacao_rspsta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='NmroWhtsApp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
