# Generated by Django 4.2.4 on 2025-05-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0010_alter_notificacao_nmrowhtsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='Pet',
        ),
        migrations.CreateModel(
            name='Pet_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_Raca', models.CharField(blank=True, max_length=140, null=True)),
                ('Pet_Nome', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('dt_Nscmnto', models.DateTimeField(blank=True, null=True)),
                ('Pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.pet')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='Pet_Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.pet_cliente'),
        ),
    ]
