# Generated by Django 4.2.4 on 2025-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_remove_consulta_pet_pet_cliente_consulta_pet_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_cliente',
            name='Pet_Sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Femea'), ('I', 'Indefindio')], default='I', max_length=1),
        ),
    ]
