# Generated by Django 4.2.4 on 2025-05-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_pet_cliente_pet_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='Pet_Foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pet'),
        ),
    ]
