# Generated by Django 4.2.4 on 2025-05-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_consulta_pet_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='Pet_Foto',
        ),
        migrations.AddField(
            model_name='pet_cliente',
            name='Pet_Foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pet'),
        ),
    ]
