# Generated by Django 4.2.4 on 2025-05-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_remove_consulta_pet_foto_pet_cliente_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_cliente',
            name='dt_Nscmnto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
