# Generated by Django 4.2.4 on 2025-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_alter_pet_cliente_dt_nscmnto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
