# Generated by Django 4.2.4 on 2025-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0016_alter_notificacao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_cliente',
            name='Pet_Pelagem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
