# Generated by Django 4.2.4 on 2025-04-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_datasabertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(max_length=175)),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones')),
            ],
        ),
        migrations.CreateModel(
            name='procedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=175)),
                ('detalhe', models.TextField(blank=True, null=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones')),
            ],
        ),
    ]
