# Generated by Django 4.2.4 on 2025-04-07 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UfEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UfEstados', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Endereco', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=125)),
                ('Cidade', models.CharField(max_length=175)),
                ('Country', models.CharField(default='Brasil', max_length=100)),
                ('CEP', models.CharField(max_length=15)),
                ('Celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('TelFixo', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
                ('RG', models.ImageField(upload_to='rgs')),
                ('CPF', models.CharField(max_length=14)),
                ('Foto', models.ImageField(upload_to='fotos_perfil')),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('Empresa', models.CharField(default='SOME STRING', max_length=200)),
                ('Cargo', models.CharField(default='SOME STRING', max_length=150)),
                ('UF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ufestados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
