# Generated by Django 4.2.4 on 2025-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='token',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
