# Generated by Django 4.2.4 on 2025-04-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Foto',
            new_name='foto',
        ),
    ]
