# Generated by Django 4.2.4 on 2025-04-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_foto_perfil_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='foto',
            new_name='Foto',
        ),
    ]
