# Generated by Django 4.2.4 on 2025-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_foto_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Cargo',
            field=models.CharField(default='Indefinido', max_length=150),
        ),
    ]
