# Generated by Django 4.2.4 on 2025-08-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_alter_perfil_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prfl_Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Endereco', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=125)),
                ('Cidade', models.CharField(max_length=175)),
                ('Country', models.CharField(default='Brasil', max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('UF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ufestados')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
