# Generated by Django 4.2.4 on 2025-08-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_prfl_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfl_endereco',
            name='urlGgleMaps',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
