# Generated by Django 4.2.4 on 2025-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_prfl_endereco_urlgglemaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfl_endereco',
            name='Complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prfl_endereco',
            name='Numero',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='prfl_endereco',
            name='Referencia',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
    ]
